### ISSUE TITLE
Unresolved reference: clientTransport

### ISSUE THREAD

**Issue by akulik512** [rsocket/rsocket-cli#122]
Hi there!

I'm trying to launch the rsocket-cli on my PC, but I get this error at the very first stage when I run this command:
`./gradlew --console plain installDist`
And my error looks like this:
`> Task :compileKotlin FAILED
e: /home/akulik/IdeaProjects/Pet/rsocket-cli/src/main/kotlin/io/rsocket/cli/client.kt: (21, 41): Unresolved reference: clientTransport
e: /home/akulik/IdeaProjects/Pet/rsocket-cli/src/main/kotlin/io/rsocket/cli/client.kt: (46, 32): Unresolved reference: clientTransport
`
You can find the full log by this [link](https://gist.github.com/akulik512/72ccc46d779693be223ea9035dbe66dc).

What is more interesting these lines of code is burning red in my IDE:
![image](https://user-images.githubusercontent.com/55091941/122117770-ea9eea00-ce2f-11eb-98d9-7cc1ae529c1b.png)

I've checked this app on two PC and got the same error. Probably, this is a bug only for my Linux distro. I'm using - Fedora. I got this bug on the Fedora 33(bash)/34(zch) and on the latest rsocket-cli version.

**Comment by akulik512** [comment]
This issue should be fixed after these changes are released - https://github.com/rsocket/rsocket-kotlin/issues/163

**Comment by yschimke** [comment]
Fixed https://github.com/rsocket/rsocket-cli/pull/123

Sorry for the delays, there was a ton of work upstream while people have been busy with summer, covid and real lives. Let me know if it works for you.

**Comment by akulik512** [comment]
Hello @yschimke !
Sorry for the long answer. Yes, looks like the issue was fixed! Thx a lot!
```bash
❯ ./gradlew --console plain installDist
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :kaptGenerateStubsKotlin UP-TO-DATE
> Task :kaptKotlin UP-TO-DATE
> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :installDist UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 565ms
9 actionable tasks: 9 up-to-date

```
