### ISSUE TITLE
Add a repl mode

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-cli#33]
cc @mitermayer any wishlist?

**Comment by yschimke** [comment]
what would the commands be like?

> stream "input payload" --md "metadata payload"
stream 1 created

> request 1 100
requested 100 credits

out> 1
out> 2
...
out> 100

**Comment by mitermayer** [comment]
I think being able to send a multiline payload as plain text would be awesome. Maybe in JSON format ?

**Comment by mitermayer** [comment]
Other cool features that it could have:

- Support for being able to close / reset a connection
- Being able to send a multiline payload written in JSON

**Comment by yschimke** [comment]
Going to close this out and target a REPL based on kscript
