### ISSUE TITLE
reactivesocket -> rsocket

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-cli#35]
What needs to happen to allow this repo moving to github.com/rsocket/rsocket-cli?

**Comment by yschimke** [comment]
@benjchristensen can you fork and rename the project, I'll take over from there

I don't have permissions to do either

**Comment by benjchristensen** [comment]
Moved and renamed.

**Comment by yschimke** [comment]
@benjchristensen Since I can't close this issue, I think I'm missing owner role.
