### ISSUE TITLE
./gradlew ---console plain installDist : build command not work

### ISSUE THREAD

**Issue by Crimsonfantasy** [rsocket/rsocket-cli#81]
`./gradlew ---console plain installDist
`
it show error message:

> Unknown command-line option '---console'.

what is the correct way to build?

**Comment by yschimke** [comment]
Just use `./gradlew installDist` for now and I'll cleanup the instructions shortly.

**Comment by yschimke** [comment]
typo ---console, fixed.  Thanks.
